### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by SlaSerX** [shekenz/epg#1]
Hello how can be installed ? did u have any manual

**Comment by shekenz** [comment]
Hi !

This is my personal CMS project and it is specifically designed to work for the website [epg.works](https://www.epg.works). Hence, features are targeted specifically for the needs of the website, but feel free to modify it as you want. You would install it like that :
- Clone the repo
- run `composer install`
- run `npm install`
- configure the .env file
- run `npm run prod`
- run the migrations

Note that this is an early work in progress project, sources are poorly documented and I do not intend to provide any support just yet.

Also, have a look at my [deployment script](https://github.com/shekenz/laravel-deploy) that automates installation/updates.

Good luck !
